### ISSUE TITLE
Importing Problem

### ISSUE THREAD

**Issue by mdathersajjad** [ibaca/java10-gwt#1]
Hey we are looking to migrate our GWT app to Java10 Runtime. We don't want any java10 features we just want it to work with java10 runtime. I tried to import your project eclipse identifies it as gwt project and also identifies the module but when running it in development mode it throws java.lang.NoClassDefFoundError: javax/servlet/Servlet not found.

**Comment by ibaca** [comment]
Uhm, hi! I strongly recommend that you ask for help here https://gitter.im/gwtproject/gwt, I am in the chat too, so maybe I answer! 😉

Anyway, this is a maven project, and I personally use IntelliJ so maybe this is an eclipse configuration problem. Did it work using just `mvn package` or `mvn gwt:devmode`? I'm going to close this issue. You can answer this here or copy the answer in the gitter chat, and we will continue there.
